config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :lists do
    scope module: :lists do
      resources :tasks
    end
  end

  root to: 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :tasks, dependent: :destroy

  validates :title, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists/tasks_controller.rb
class Lists::TasksController < ApplicationController
  before_action do
    @list = List.find(params[:list_id])
  end

  # GET /lists/tasks
  def index
    @tasks = @list.tasks.all
  end

  # GET /lists/tasks/1
  def show
    @task = Task.find(params[:id])
  end

  # GET /lists/tasks/new
  def new
    @task = Task.new
  end

  # GET /lists/tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /lists/tasks
  def create
    @task = Task.new(task_params)
    @task.list = @list

    if @task.save
      redirect_to list_task_path(@list, @task), notice: 'Task was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /lists/tasks/1
  def update
    @task = Task.find(params[:id])

    if @task.update_attributes(task_params)
      redirect_to list_task_path(@list, @task), notice: 'Task was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /lists/tasks/1
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to list_tasks_path(@list)
  end

  private

  def task_params
    params.require(:task).permit!
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all

    respond_to do |format|
      format.html # show.html.erb
      format.json {render json: @lists}
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = List.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json {render json: @list}
    end
  end

  # GET /lists/new
  # GET /lists/new.json
  def new
    @list = List.new

    respond_to do |format|
      format.html # new.html.erb
      format.json {render json: @list}
    end
  end

  # GET /lists/1/edit
  def edit
    @list = List.find(params[:id])
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.create(list_params)

    respond_to do |format|
      if @list.save
        format.html {redirect_to @list, notice: 'List was successfully created.'}
        format.json {render json: @list, status: :created, location: @list}
      else
        format.html {render action: "new"}
        format.json {render json: @list.errors, status: :unprocessable_entity}
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(list_params)
        format.html {redirect_to @list, notice: 'List was successfully updated.'}
        format.json {head :no_content}
      else
        format.html {render action: "edit"}
        format.json {render json: @list.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html {redirect_to lists_url}
      format.json {head :no_content}
    end
  end

  private

  def list_params
    params.require(:list).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def date_to_str(date)
    begin
      date.strftime("%d/%m/%Y")
    rescue
      ""
    end
  end
end

app/helpers/lists/tasks_helper.rb
module Lists::TasksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoRailsTest</title>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">

    <%= stylesheet_link_tag    "application", :media => "all" %>

    <script type="text/javascript" language="javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>
      <ul>
        <% @list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

  <div class="actions float-right">
    <button type="submit" class="btn btn-primary">Submit</button>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list, class: "btn btn-primary" %>
<%= link_to 'Back', lists_path, class: "btn btn-danger" %>

app/views/lists/index.html.erb
<h1 class="page_title">Lists</h1>

<table id="example" class="table table-striped table-bordered" style="width:100%">
  <thead>
  <tr>
    <th>Title</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @lists.each do |list| %>
      <tr>
        <td><%= list.title %></td>
        <td>
          <%= link_to 'Show', list, class: "btn btn-primary" %>
          <%= link_to 'Edit', edit_list_path(list), class: "btn btn-warning" %>
          <%= link_to 'Destroy', list, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New List', new_list_path, class: "btn btn-secondary" %>

<script type="application/javascript">
    $(document).ready(function () {
        $('#example').DataTable();
    });
</script> 

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path, class: "btn btn-danger" %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @list.title %>
</p>

<%= link_to 'Tasks', list_tasks_path(@list), class: "btn btn-secondary" %>
<%= link_to 'Edit', edit_list_path(@list), class: "btn btn-primary" %>
<%= link_to 'Back', lists_path, class: "btn btn-danger" %>

app/views/lists/tasks/_form.html.erb
<%= form_for([@list, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :due_at, "Due Date" %>
      <%= f.text_field :due_at, class: "form-control datepicker" %>
    </div>

    <div class="custom-control custom-checkbox">
      <%= f.check_box :complete, class: "custom-control-input", id: "defaultUnchecked" %>
      <label class="custom-control-label" for="defaultUnchecked">Complete?</label>
    </div>

    <br>
    
    <div class="actions float-right">
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
<% end %>

<script type="text/javascript">
    $(document).ready(function () {
        $('.datepicker').datepicker();
    });
</script>

app/views/lists/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', list_task_path(@list, @task), class: "btn btn-primary" %>
<%= link_to 'Back', list_tasks_path(@list), class: "btn btn-danger" %>

app/views/lists/tasks/index.html.erb
<h1 class="page_title">List Tasks</h1>

<table id="example" class="table table-striped table-bordered" style="width:100%">
  <thead>
  <tr>
    <th>Name</th>
    <th>Due Date</th>
    <th>Complete?</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= date_to_str(task.due_at) %></td>
        <td><%= task.complete %></td>
        <td>
          <%= link_to 'Show', list_task_path(@list, task), class: "btn btn-primary" %>
          <%= link_to 'Edit', edit_list_task_path(@list, task), class: "btn btn-warning" %>
          <%= link_to 'Destroy', list_task_path(@list, task), method: :delete, confirm: 'Are you sure?', class: "btn btn-danger" %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>


<br/>
<%= link_to 'Back', lists_path, class: "btn btn-danger"  %>
<%= link_to 'New Task', new_list_task_path(@list), class: "btn btn-secondary float-right"  %>

<script type="application/javascript">
    $(document).ready(function () {
        $('#example').DataTable();
    });
</script>

app/views/lists/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', list_tasks_path(@list), class: "btn btn-danger" %>

app/views/lists/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Due Date:</b>
  <%= date_to_str(@task.due_at) %>
</p>

<p>
  <b>Complete?</b>
  <%= @task.complete %>
</p>

<%= link_to 'Edit', edit_list_task_path(@list, @task), class: "btn btn-primary" %>
<%= link_to 'Back', list_tasks_path(@list), class: "btn btn-danger" %>